server:
  port: 9528

spring:
  datasource:
    url: jdbc:mysql://192.168.31.217:3306/tb_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  activemq:
    broker-url: tcp://localhost:61616
